### ISSUE TITLE
When to call function?

### ISSUE THREAD

**Issue by vespino** [EddyVerbruggen/cordova-plugin-touch-id#5]
When do I call this function? I'm currently building an app which asks users for user and pass. I would love to add touchid but when should I first ask for fingerprint? After the first login I guess to be able to match fingerprint with credentials?

Does it work with PGB btw?

**Comment by EddyVerbruggen** [comment]
That's up to you of course. But I think you're on the right track. Have them authenticate first and then ask if they want to add their fp. Note that you can't match a fp with credentials since the Touch ID framework only returns true or false (recognized or not). So if your app is multi-user you need to get creative (have them pick a profile before or after scanning), and that would only work if it's no problem if they would select a different profile by mistake. If the app is single user then it should be straightfwd.

And it should work fine with pgb, never tested that though.

**Comment by vespino** [comment]
I guess that's a flaw in touchid, it allows for users to login to apps if the fp is present, even if access to the app should not be granted. This shows iOS is made for single user use only I guess.

I think I will let it go for this project and first gather more information on the topic.
